# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Aaron Train
tagline:          Mozilla QE Engineer
description:      'Sr. QE Engineer @ <a href="http://www.mozilla.org">Mozilla</a>'
url:              http://aaronmt.com
author:
  name:           Aaron Train
  email:          atrain@mozilla.com
  url:            http://aaronmt.com
  github:         https://github.com/aaronmt
  twitter:        http://twitter.com/aaronmt
  googleplus:     https://plus.google.com/+AaronTrain/
  irc:            irc://irc.mozilla.org/QA

paginate:         1

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/aaronmt/

# Analytics
analytics:
  provider:       google
  google:
    tracking_id: 'UA-53554008-1'
